"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ShieldCheck, UsersRound } from "lucide-react";
import type { AdminUserPage, AdminUserView, DepartmentAdministrationView, GovernanceSummary } from "@/domain/administration";
import { UserRole } from "@/domain/model";

function readable(value: string) { return value.toLowerCase().split("_").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" "); }
function stamp(value: string | Date) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

function UserRow({ user, departments, currentUserId, onSaved }: { user: AdminUserView; departments: DepartmentAdministrationView[]; currentUserId: string; onSaved: (user: AdminUserView) => void }) {
  const [role, setRole] = useState(user.role); const [departmentId, setDepartmentId] = useState(user.department.id); const [active, setActive] = useState(user.active); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false);
  const protectedSelf = user.id === currentUserId;
  const save = async () => { setBusy(true); setError(null); setSaved(false); try { const response = await fetch(`/api/admin/users/${user.id}`, { method: "PATCH", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ role, departmentId, active }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to update operator."); onSaved({ ...user, role, active, department: departments.find((department) => department.id === departmentId) ?? user.department, updatedAt: new Date() }); setSaved(true); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to update operator."); } finally { setBusy(false); } };
  return <li className="admin-user-row"><div className="admin-user-identity"><strong>{user.displayName}</strong><span>{user.email}</span><small>Created {stamp(user.createdAt)} · Updated {stamp(user.updatedAt)}</small></div><label>Role<select aria-label={`${user.displayName} role`} value={role} disabled={protectedSelf} onChange={(event) => setRole(event.target.value as UserRole)}>{Object.values(UserRole).map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label><label>Department<select aria-label={`${user.displayName} department`} value={departmentId} disabled={protectedSelf} onChange={(event) => setDepartmentId(event.target.value)}>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label className="admin-active">Active<input aria-label={`${user.displayName} active`} type="checkbox" checked={active} disabled={protectedSelf} onChange={(event) => setActive(event.target.checked)} /></label><div className="admin-user-action"><button className="secondary-button" type="button" disabled={protectedSelf || busy} onClick={() => void save()}>{busy ? "Saving…" : "Save"}</button>{protectedSelf ? <small>Own access is protected here.</small> : null}{saved ? <small className="admin-save-success" role="status">Saved and audited.</small> : null}{error ? <small className="form-error">{error}</small> : null}</div></li>;
}

export function AdministrationConsole({ initialUsers, departments, governance, currentUserId }: { initialUsers: AdminUserPage; departments: DepartmentAdministrationView[]; governance: GovernanceSummary; currentUserId: string }) {
  const [users, setUsers] = useState(initialUsers.items); const [cursor, setCursor] = useState(initialUsers.nextCursor); const [filters, setFilters] = useState({ q: "", role: "", departmentId: "", active: "" }); const [loading, setLoading] = useState(false); const query = useMemo(() => new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString(), [filters]);
  const load = async (append = false, cursorValue?: string | null) => { setLoading(true); try { const params = new URLSearchParams(query); params.set("limit", "25"); if (cursorValue) params.set("cursor", cursorValue); const response = await fetch(`/api/admin/users?${params}`, { credentials: "same-origin" }); const payload: AdminUserPage & { error?: string } = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to load operators."); setUsers((current) => append ? [...current, ...payload.items] : payload.items); setCursor(payload.nextCursor); } finally { setLoading(false); } };
  const apply = () => void load();
  return <div className="admin-console"><section className="admin-section"><header className="panel-heading"><div><p className="panel-kicker">Restricted operator management</p><h2>Users</h2><p>Role, department, and activation changes are validated and permanently audited.</p></div><UsersRound aria-hidden="true" /></header><form className="admin-filters" onSubmit={(event) => { event.preventDefault(); apply(); }}><label>Search<input value={filters.q} onChange={(event) => setFilters((current) => ({ ...current, q: event.target.value }))} placeholder="Name or email" /></label><label>Role<select value={filters.role} onChange={(event) => setFilters((current) => ({ ...current, role: event.target.value }))}><option value="">All roles</option>{Object.values(UserRole).map((role) => <option key={role} value={role}>{readable(role)}</option>)}</select></label><label>Department<select value={filters.departmentId} onChange={(event) => setFilters((current) => ({ ...current, departmentId: event.target.value }))}><option value="">All departments</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label>Status<select value={filters.active} onChange={(event) => setFilters((current) => ({ ...current, active: event.target.value }))}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button className="secondary-button" type="submit">Filter</button></form><ul className="admin-user-list">{users.map((user) => <UserRow key={user.id} user={user} departments={departments} currentUserId={currentUserId} onSaved={(updated) => setUsers((current) => current.map((user) => user.id === updated.id ? updated : user))} />)}</ul>{users.length === 0 ? <p className="admin-empty">No operators match this authorized filter.</p> : null}{cursor ? <button className="secondary-button" type="button" disabled={loading} onClick={() => void load(true, cursor)}>{loading ? "Loading…" : "Load more operators"}</button> : null}</section>
    <section className="admin-section"><header className="panel-heading"><div><p className="panel-kicker">Authorized organization context</p><h2>Departments</h2><p>Read-only operational context; department deletion and unbounded changes are intentionally unavailable.</p></div></header><div className="department-grid">{departments.map((department) => <article key={department.id}><strong>{department.name}</strong><span>{department.code}</span><dl><div><dt>Members</dt><dd>{department.memberCount} ({department.activeMemberCount} active)</dd></div><div><dt>Cases</dt><dd>{department.caseCount}</dd></div><div><dt>Incidents</dt><dd>{department.incidentCount}</dd></div><div><dt>Findings</dt><dd>{department.findingCount}</dd></div></dl></article>)}</div></section>
    <section className="admin-section"><header className="panel-heading"><div><p className="panel-kicker">Verification coordination</p><h2>Governance</h2><p>Review the responsible source workspace before making a verification decision.</p></div><ShieldCheck aria-hidden="true" /></header><div className="governance-grid"><Link href="/incidents"><strong>{governance.departmentVerifiedIncidents}</strong><span>Department-verified incidents</span></Link><Link href="/incidents"><strong>{governance.crossVerifiedIncidents}</strong><span>Cross-verified incidents</span></Link><Link href="/incidents"><strong>{governance.openIncidentReviews}</strong><span>Open incident reviews</span></Link><Link href="/investigations"><strong>{governance.escalatedFindings}</strong><span>Escalated findings</span></Link></div></section></div>;
}
