"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import type { IncidentSummary, TimelineItem } from "@/domain/incident";
import type { WorkspaceLayoutItem } from "@/domain/workspace";
import { TimelineList } from "@/features/incidents/timeline-list";
import { WorkspaceGrid } from "@/features/workspace/workspace-grid";
import { FindingDetail, FindingHistory, FindingLinks, SupportingEvidence, readable, timestamp, type Finding } from "./finding-panels";

type Person = { id: string; displayName: string };
type CaseOption = { id: string; firNumber: string };
type Department = { id: string; name: string };
type Metric = { label: string; value: string; detail: string };
type Analysis = { timeline: Array<Omit<TimelineItem, "timestamp"> & { timestamp: string }>; findings: Array<{ title: string; detail: string; reviewStatus: string }>; communicationMetrics: Metric[]; financialMetrics: Metric[]; networkMetrics: Metric[]; crossCaseMetrics: Metric[] };
type Quality = { total: number; reviewed: number; unreviewed: number; acknowledged: number; dismissed: number; falsePositive: number; needsMoreEvidence: number; escalated: number; averageTurnaroundHours: number | null; medianTurnaroundHours: number | null; byType: Array<{ category: string; count: number }>; dispositionTrend: Array<{ date: string; status: string; count: number }> };

const reviewStates = ["", "UNREVIEWED", "UNDER_REVIEW", "ACKNOWLEDGED", "NEEDS_MORE_EVIDENCE", "DISMISSED", "ESCALATED"];
const categories = ["COMMUNICATION", "FINANCIAL", "NETWORK", "CROSS_CASE"];
const verificationLevels = ["UNVERIFIED", "DEPARTMENT_VERIFIED", "CROSS_VERIFIED"];
const dispositionReasons = ["RELEVANT_TO_CASE", "SUPPORTS_EXISTING_LEAD", "REQUIRES_FOLLOW_UP", "INSUFFICIENT_HISTORY", "WEAK_PROVENANCE", "MISSING_SOURCE_RECORD", "REQUIRES_DEPARTMENT_INPUT", "EXPECTED_BEHAVIOR", "DUPLICATE_FINDING", "DATA_QUALITY_ISSUE", "FALSE_POSITIVE", "NOT_RELEVANT_TO_CASE", "CROSS_CASE_RELEVANCE", "CROSS_DEPARTMENT_RELEVANCE", "REQUIRES_SUPERVISOR_REVIEW", "REQUIRES_ADMIN_CROSS_VERIFICATION"];

function MetricPanel({ title, metrics }: { title: string; metrics: Metric[] }) {
  return <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Deterministic comparison</p><h2>{title}</h2></header><dl className="investigation-metrics">{metrics.map((metric) => <div key={metric.label}><dt>{metric.label}</dt><dd>{metric.value}</dd><p>{metric.detail}</p></div>)}</dl></section>;
}

export function InvestigationWorkspace({ people, incidents, cases = [], departments = [], canAttachEvidence = false, initialItems }: { people: Person[]; incidents: IncidentSummary[]; cases?: CaseOption[]; departments?: Department[]; canAttachEvidence?: boolean; initialItems: WorkspaceLayoutItem[] }) {
  const [filters, setFilters] = useState({ status: "", category: "", personId: "", incidentId: "", caseId: "", departmentId: "", verificationLevel: "", startTime: "", endTime: "" });
  const [queue, setQueue] = useState<Finding[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [selected, setSelected] = useState<Finding | null>(null); const [quality, setQuality] = useState<Quality | null>(null); const [error, setError] = useState<string | null>(null);
  const [sourceType, setSourceType] = useState("ALL"); const [reasonCode, setReasonCode] = useState("REQUIRES_FOLLOW_UP"); const [reviewNote, setReviewNote] = useState("");
  const [personId, setPersonId] = useState(people[0]?.id ?? ""); const [incidentId, setIncidentId] = useState(incidents[0]?.id ?? ""); const [beforeDays, setBeforeDays] = useState("7"); const [afterDays, setAfterDays] = useState("2"); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState<string | null>(null);
  const query = useCallback((cursorValue?: string | null) => { const params = new URLSearchParams({ limit: "25" }); for (const [key, value] of Object.entries({ ...filters, cursor: cursorValue ?? "" })) if (value) params.set(key, value); return params; }, [filters]);
  const loadQueue = useCallback(async (append = false, cursorValue?: string | null) => { try { const response = await fetch(`/api/investigations/findings?${query(cursorValue)}`, { credentials: "same-origin" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to load findings."); setQueue((current) => append ? [...current, ...payload.items] : payload.items); setCursor(payload.nextCursor); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load findings."); } }, [query]);
  useEffect(() => { const timer = setTimeout(() => void loadQueue(), 0); return () => clearTimeout(timer); }, [loadQueue]);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => { void fetch("/api/investigations/metrics", { credentials: "same-origin", signal: controller.signal }).then((response) => response.json()).then(setQuality).catch(() => undefined); }, 0); return () => { clearTimeout(timer); controller.abort(); }; }, []);
  const setFilter = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const selectFinding = async (finding: Finding) => { const response = await fetch(`/api/investigations/findings/${finding.persistentId}`, { credentials: "same-origin" }); const payload = await response.json(); if (response.ok) { setSelected(payload); setSourceType("ALL"); } else setError(payload.error ?? "Unable to load finding."); };
  const review = async (status: string) => { if (!selected) return; const response = await fetch(`/api/investigations/findings/${selected.persistentId}/review`, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, reasonCode, note: reviewNote }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error ?? "Unable to record review."); return; } setSelected(payload); setReviewNote(""); setQueue((current) => current.map((finding) => finding.persistentId === payload.persistentId ? payload : finding)); void loadQueue(); };
  const run = async () => { const response = await fetch(`/api/investigations/analyze?${new URLSearchParams({ personId, incidentId, beforeDays, afterDays })}`, { credentials: "same-origin" }); const payload = await response.json(); if (response.ok) { setAnalysis(payload); void loadQueue(); } else setError(payload.error ?? "Unable to load analysis."); };
  const ask = async () => { const response = await fetch("/api/investigations/copilot", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ personId, incidentId, beforeDays: Number(beforeDays), afterDays: Number(afterDays), question, findingId: selected?.persistentId }) }); const payload = await response.json(); if (response.ok) setAnswer(payload.answer); else setError(payload.error ?? "Unable to answer."); };
  const timeline = useMemo(() => analysis?.timeline.map((item) => ({ ...item, timestamp: new Date(item.timestamp) })) ?? [], [analysis]);

  const queuePanel = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Persisted operations</p><h2>Findings queue</h2></header><div className="investigation-controls finding-filters">
    <label>Review status<select aria-label="Review status filter" value={filters.status} onChange={(event) => setFilter("status", event.target.value)}>{reviewStates.map((value) => <option key={value} value={value}>{value ? readable(value) : "All authorized findings"}</option>)}</select></label><label>Type<select aria-label="Finding type filter" value={filters.category} onChange={(event) => setFilter("category", event.target.value)}><option value="">All types</option>{categories.map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label><label>Person<select aria-label="Person filter" value={filters.personId} onChange={(event) => setFilter("personId", event.target.value)}><option value="">All people</option>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label>Incident<select aria-label="Incident filter" value={filters.incidentId} onChange={(event) => setFilter("incidentId", event.target.value)}><option value="">All incidents</option>{incidents.map((incident) => <option key={incident.id} value={incident.id}>{incident.incidentNumber}</option>)}</select></label><label>Case / FIR<select aria-label="Case filter" value={filters.caseId} onChange={(event) => setFilter("caseId", event.target.value)}><option value="">All cases</option>{cases.map((record) => <option key={record.id} value={record.id}>{record.firNumber}</option>)}</select></label><label>Department<select aria-label="Department filter" value={filters.departmentId} onChange={(event) => setFilter("departmentId", event.target.value)}><option value="">All authorized departments</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label>Verification<select aria-label="Verification filter" value={filters.verificationLevel} onChange={(event) => setFilter("verificationLevel", event.target.value)}><option value="">All levels</option>{verificationLevels.map((value) => <option key={value} value={value}>{readable(value)}</option>)}</select></label><label>Generated after<input aria-label="Generated after" type="date" value={filters.startTime} onChange={(event) => setFilter("startTime", event.target.value)} /></label><label>Generated before<input aria-label="Generated before" type="date" value={filters.endTime} onChange={(event) => setFilter("endTime", event.target.value)} /></label>
  </div>{queue.length === 0 ? <EmptyState title="No authorized findings" description="No persisted finding matches this authorized filter." /> : <ul className="investigation-findings">{queue.map((finding) => <li key={finding.persistentId}><button className="finding-select" onClick={() => void selectFinding(finding)}><strong>{readable(finding.category)} · {finding.title}</strong><p>{finding.personName} · {finding.incidentNumber} · {finding.caseFirNumber ?? "No FIR"}</p><p>{finding.detail}</p><p>{timestamp(finding.generatedAt)} · {finding.supportingRecordIds.length} sources · {finding.verificationLevels.map(readable).join(", ") || "No verification state"}</p></button><div><StatusBadge tone={finding.reviewStatus === "ESCALATED" ? "warning" : "neutral"}>{readable(finding.reviewStatus)}</StatusBadge></div></li>)}</ul>}{cursor ? <button onClick={() => void loadQueue(true, cursor)}>Load more</button> : null}</section>;
  const detail = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Finding detail</p><h2>{selected?.title ?? "Select a finding"}</h2></header>{selected ? <FindingDetail finding={selected} sourceType={sourceType} /> : <EmptyState title="No finding selected" description="Select an authorized queue item to view transparent rationale and provenance." />}</section>;
  const history = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Immutable record</p><h2>Review history</h2></header>{selected ? <FindingHistory finding={selected} /> : <EmptyState title="No history selected" description="Choose an authorized finding to inspect preserved review events." />}</section>;
  const evidencePanel = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Authorized provenance</p><h2>Supporting evidence</h2></header>{selected ? <SupportingEvidence finding={selected} sourceType={sourceType} /> : <EmptyState title="No evidence context selected" description="Select a finding, then inspect its authorized sources and evidence." />}</section>;
  const followUp = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Explicit human action</p><h2>Follow-up actions</h2></header>{!selected ? <EmptyState title="Select a finding" description="Actions are enabled only for a selected authorized finding." /> : <><FindingLinks finding={selected} canAttachEvidence={canAttachEvidence} inspect={setSourceType} /><div className="finding-review-form"><label>Structured reason<select value={reasonCode} onChange={(event) => setReasonCode(event.target.value)}>{dispositionReasons.map((reason) => <option key={reason} value={reason}>{readable(reason)}</option>)}</select></label><label>Reviewer note<textarea value={reviewNote} maxLength={2000} onChange={(event) => setReviewNote(event.target.value)} /></label></div><div className="finding-actions"><button onClick={() => review("UNDER_REVIEW")}>Start review</button><button onClick={() => review("ACKNOWLEDGED")}>Acknowledge</button><button onClick={() => review("NEEDS_MORE_EVIDENCE")}>Needs more evidence</button><button onClick={() => review("DISMISSED")}>Dismiss</button><button onClick={() => review("ESCALATED")}>Escalate</button></div><p className="workspace-widget-muted">These actions record a human disposition. They cannot verify the lead or its underlying intelligence.</p></>}</section>;
  const reviewMetrics = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Descriptive only</p><h2>Review metrics</h2></header>{!quality ? <p>Loading…</p> : <dl className="investigation-metrics">{[["Total", quality.total], ["Reviewed", quality.reviewed], ["Unreviewed", quality.unreviewed], ["Acknowledged", quality.acknowledged], ["Dismissed", quality.dismissed], ["False positive", quality.falsePositive], ["Needs evidence", quality.needsMoreEvidence], ["Escalated", quality.escalated], ["Average turnaround", quality.averageTurnaroundHours === null ? "—" : `${quality.averageTurnaroundHours}h`], ["Median turnaround", quality.medianTurnaroundHours === null ? "—" : `${quality.medianTurnaroundHours}h`]].map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd>{String(value)}</dd></div>)}</dl>}<p className="workspace-widget-muted">By type: {(quality?.byType ?? []).map((item) => `${readable(item.category)} ${item.count}`).join(" · ") || "—"}. Review trend: {(quality?.dispositionTrend ?? []).map((item) => `${item.date} ${readable(item.status)} ${item.count}`).join(" · ") || "—"}. No personnel ranking or automatic threshold changes.</p></section>;
  const context = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Controlled analysis</p><h2>Incident window</h2><p>Select an incident window to run bounded authorized analysis.</p></header><div className="investigation-controls"><label>Person<select value={personId} onChange={(event) => setPersonId(event.target.value)}>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label>Incident<select value={incidentId} onChange={(event) => setIncidentId(event.target.value)}>{incidents.map((incident) => <option key={incident.id} value={incident.id}>{incident.incidentNumber}</option>)}</select></label><label>Days before<input aria-label="Days before incident" type="number" min="1" max="90" value={beforeDays} onChange={(event) => setBeforeDays(event.target.value)} /></label><label>Days after<input aria-label="Days after incident" type="number" min="0" max="30" value={afterDays} onChange={(event) => setAfterDays(event.target.value)} /></label><button onClick={run}>Run analysis</button></div>{error ? <p className="form-error">{error}</p> : null}</section>;
  const copilot = <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Read-only</p><h2>Investigation copilot</h2><p>{selected ? `Review context: ${selected.title}` : "Analysis context only"}</p></header><label className="copilot-question">Question<input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Why was this finding dismissed?" /></label><button onClick={ask}>Ask controlled copilot</button>{answer ? <div className="copilot-answer"><StatusBadge tone="warning">INVESTIGATIVE LEAD — HUMAN REVIEW REQUIRED</StatusBadge><p>{answer}</p></div> : null}</section>;
  const statusPanel = (status: string, count: number | undefined) => <section className="workspace-widget-panel investigation-panel"><header><p className="panel-kicker">Authorized review lane</p><h2>{readable(status)}</h2></header><p className="review-lane-count">{count ?? "—"}</p><button onClick={() => setFilter("status", status)}>Open in Findings Queue</button></section>;
  const widgets = [{ id: "findings-queue", content: queuePanel }, { id: "finding-detail", content: detail }, { id: "review-history", content: history }, { id: "supporting-evidence", content: evidencePanel }, { id: "follow-up-actions", content: followUp }, { id: "review-metrics", content: reviewMetrics }, { id: "escalated-findings", content: statusPanel("ESCALATED", quality?.escalated) }, { id: "needs-more-evidence", content: statusPanel("NEEDS_MORE_EVIDENCE", quality?.needsMoreEvidence) }, { id: "investigation-context", content: context }, { id: "investigation-findings", content: <MetricPanel title="Current analysis leads" metrics={(analysis?.findings ?? []).map((finding) => ({ label: finding.title, value: finding.reviewStatus, detail: finding.detail }))} /> }, { id: "investigation-timeline", content: <TimelineList items={timeline} title="Unified timeline" /> }, { id: "communication-changes", content: <MetricPanel title="Communication changes" metrics={analysis?.communicationMetrics ?? []} /> }, { id: "financial-changes", content: <MetricPanel title="Financial changes" metrics={analysis?.financialMetrics ?? []} /> }, { id: "network-changes", content: <MetricPanel title="Network changes" metrics={analysis?.networkMetrics ?? []} /> }, { id: "cross-case-links", content: <MetricPanel title="Cross-case context" metrics={analysis?.crossCaseMetrics ?? []} /> }, { id: "investigation-copilot", content: copilot }];
  return <WorkspaceGrid workspaceKey="investigation" initialItems={initialItems} widgets={widgets} ariaLabel="Investigation workspace panels" maxColumns={2} cellSize={360} />;
}
