"use client";

import Link from "next/link";
import { ArrowRight, Clock3, Crosshair, FileSearch, MapPin, ShieldCheck } from "lucide-react";
import type { GraphEntityType } from "@/domain/model";
import type { SerializedGeographicConnection, SerializedGeographicProjection } from "./geographic-view-model";
import type { SerializedRelationshipDetail } from "./graph-view-model";

export function titleCase(value: string): string {
  return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function formatMoment(value: string | null): string {
  if (!value) return "Not recorded";
  return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }).format(new Date(value)) + " UTC";
}

export function EventTimeline({ projection, onWindowSelect }: { projection: SerializedGeographicProjection; onWindowSelect: (start: string, end: string) => void }) {
  const items = projection.timeline.slice(0, 10);
  const chooseWindow = (timestamp: string) => {
    const center = new Date(timestamp).getTime();
    onWindowSelect(new Date(center - 12 * 60 * 60 * 1_000).toISOString(), new Date(center + 12 * 60 * 60 * 1_000).toISOString());
  };
  return <section id="network-timeline" className="network-timeline" aria-label="Event timeline"><header><span className="eyebrow">Event timeline</span><strong>{items.length} recent authorized events</strong></header><div className="network-timeline-track">{items.length === 0 ? <div className="network-inline-empty"><strong>NO TIMELINE EVENTS</strong><span>No timeline events are available for the selected period.</span></div> : items.map((item) => <button key={item.id} type="button" onClick={() => chooseWindow(item.timestamp)} title={item.description}><i /><span>{titleCase(item.type)}</span><strong>{item.title}</strong><time>{formatMoment(item.timestamp)}</time></button>)}</div></section>;
}

export function InvestigationContext({ projection }: { projection: SerializedGeographicProjection }) {
  return <section className="network-rail-panel"><header><Crosshair aria-hidden="true" /><div><span className="eyebrow">Investigation context</span><h2>{projection.focusEntity.displayLabel}</h2></div></header><dl className="network-compact-facts"><div><dt>Entity</dt><dd>{titleCase(projection.focusEntity.entityType)}</dd></div><div><dt>Visible network</dt><dd>{projection.graph.nodes.length} entities / {projection.graph.edges.length} links</dd></div><div><dt>Observations</dt><dd>{projection.observations.length} authorized</dd></div><div><dt>Time window</dt><dd>Bounded projection</dd></div></dl></section>;
}

export function ActivityQueue({ projection, onConnectionSelect }: { projection: SerializedGeographicProjection; onConnectionSelect: (id: string) => void }) {
  const items = projection.connections.filter((item) => item.records.length > 0).slice(0, 6);
  return <section className="network-rail-panel"><header><Clock3 aria-hidden="true" /><div><span className="eyebrow">Activity queue</span><h2>Recent connections</h2></div></header>{items.length === 0 ? <p className="workspace-widget-muted">No connection activity matches this scope.</p> : <ol className="network-activity-list">{items.map((item) => <li key={item.id}><button type="button" onClick={() => onConnectionSelect(item.id)}><span>{item.sourceLabel} <ArrowRight aria-hidden="true" size={11} /> {item.targetLabel}</span><small>{item.records.length} source record{item.records.length === 1 ? "" : "s"}</small></button></li>)}</ol>}</section>;
}

export function SelectedEntityPanel({ projection, entityId, onFocus }: { projection: SerializedGeographicProjection; entityId: string | null; onFocus: (id: string) => void }) {
  const entity = projection.graph.nodes.find((item) => item.id === entityId) ?? projection.focusEntity;
  const observations = projection.observations.filter((item) => item.graphEntityId === entity.id);
  const edges = projection.graph.edges.filter((edge) => edge.sourceId === entity.id || edge.targetId === entity.id);
  const connections = projection.connections.filter((connection) => connection.sourceEntityId === entity.id || connection.targetEntityId === entity.id);
  const neighborIds = new Set(edges.map((edge) => edge.sourceId === entity.id ? edge.targetId : edge.sourceId));
  const neighbors = projection.graph.nodes.filter((node) => neighborIds.has(node.id));
  const relatedCases = new Map<string, string>();
  for (const connection of connections) for (const record of connection.records) if (record.caseId && record.caseFirNumber) relatedCases.set(record.caseId, record.caseFirNumber);
  for (const neighbor of neighbors) if (neighbor.canonicalRecord?.type === "CASE") relatedCases.set(neighbor.canonicalRecord.id, neighbor.displayLabel);
  const relationshipTypes = [...new Set(edges.map((edge) => titleCase(edge.relationshipType)))];
  const tier = edges.some((edge) => edge.strength === "PRIMARY") ? "Primary" : edges.some((edge) => edge.strength === "SECONDARY") ? "Secondary" : edges.some((edge) => edge.strength === "TERTIARY") ? "Tertiary" : "No visible relationship";
  const incidentEvents = projection.timeline.filter((item) => item.type === "INCIDENT" && (item.incidentId === entity.canonicalRecord?.id || item.personIds.includes(entity.canonicalRecord?.id ?? "")));
  const linkedAssetCount = (types: GraphEntityType[]) => neighbors.filter((node) => types.includes(node.entityType)).length;
  const canonicalHref = entity.canonicalRecord?.type === "PERSON" ? `/people/${entity.canonicalRecord.id}` : entity.canonicalRecord?.type === "CASE" ? `/cases/${entity.canonicalRecord.id}` : entity.canonicalRecord?.type === "INCIDENT" ? `/incidents/${entity.canonicalRecord.id}` : null;
  return <section className="network-rail-panel"><header><MapPin aria-hidden="true" /><div><span className="eyebrow">Selected entity</span><h2>{entity.displayLabel}</h2></div></header><dl className="network-compact-facts"><div><dt>Type</dt><dd>{titleCase(entity.entityType)}</dd></div><div><dt>Verification</dt><dd>{titleCase(entity.verificationState)}</dd></div><div><dt>Relationship context</dt><dd>{tier}{relationshipTypes.length ? ` · ${relationshipTypes.slice(0, 2).join(", ")}` : ""}</dd></div><div><dt>Visible connections</dt><dd>{connections.length}</dd></div><div><dt>Geographic observations</dt><dd>{observations.length}</dd></div><div><dt>Related Case/FIR</dt><dd>{relatedCases.size ? [...relatedCases.values()].slice(0, 2).join(", ") : "None in current scope"}</dd></div><div><dt>Relevant incidents</dt><dd>{neighbors.filter((node) => node.entityType === "INCIDENT").length || incidentEvents.length}</dd></div>{incidentEvents[0] ? <div><dt>Latest incident context</dt><dd>{incidentEvents[0].title} · {formatMoment(incidentEvents[0].timestamp)}</dd></div> : null}<div><dt>Properties</dt><dd>{linkedAssetCount(["PROPERTY" as GraphEntityType])}</dd></div><div><dt>Vehicles / devices</dt><dd>{linkedAssetCount(["VEHICLE" as GraphEntityType, "DEVICE" as GraphEntityType])}</dd></div></dl>{observations.length ? <ol className="network-entity-observations">{observations.slice(0, 3).map((observation) => <li key={observation.id}><strong>{titleCase(observation.observationType)} · {observation.locationLabel}</strong><span>{formatMoment(observation.observedAt)} · {titleCase(observation.verificationLevel)}</span><span>Source {titleCase(observation.sourceRecordType)} · {observation.sourceRecordId}</span>{observation.sourceEvidenceId ? <Link href={`/api/evidence/${observation.sourceEvidenceId}`} target="_blank">Inspect evidence</Link> : <span>Evidence source unavailable</span>}</li>)}</ol> : <div className="network-inline-empty"><strong>NO GEOLOCATION</strong><span>No geographic observations are available for the selected entity and time window.</span></div>}<div className="network-panel-actions">{canonicalHref ? <Link href={canonicalHref}>Open {entity.canonicalRecord?.type === "PERSON" ? "profile" : titleCase(entity.canonicalRecord?.type ?? "record")}</Link> : null}{[...relatedCases].slice(0, 1).map(([id, fir]) => <Link key={id} href={`/cases/${id}`}>Open {fir}</Link>)}{entity.id !== projection.focusEntity.id ? <button type="button" onClick={() => onFocus(entity.id)}>Make shared focus</button> : null}</div></section>;
}

function LocationResolution({ label, status, location, distance }: { label: string; status: "KNOWN" | "UNKNOWN"; location: string | null; distance: number | null }) {
  return <div className={status === "KNOWN" ? "is-known" : "is-unknown"}><dt>{label}</dt><dd>{status === "KNOWN" ? location : "LOCATION UNKNOWN"}{distance !== null ? <small>{distance}s from event time</small> : status === "UNKNOWN" ? <small>A geographic relationship exists, but the location cannot be resolved from authorized observations.</small> : null}</dd></div>;
}

export function ConnectionDetailsPanel({ connection, relationshipDetails, provenanceLoading }: { connection: SerializedGeographicConnection | null; relationshipDetails: Record<string, SerializedRelationshipDetail>; provenanceLoading: boolean }) {
  if (!connection) return <section className="network-rail-panel"><header><FileSearch aria-hidden="true" /><div><span className="eyebrow">Connection details</span><h2>NO CONNECTION SELECTED</h2></div></header><p className="workspace-widget-muted">Select a map or relationship connection to inspect why NexusTrace shows it.</p></section>;
  const relationshipInteractions = connection.records.filter((record) => record.kind === "RELATIONSHIP").reduce((total, record) => total + record.interactionCount, 0);
  const activityInteractions = connection.records.filter((record) => record.kind !== "RELATIONSHIP").reduce((total, record) => total + record.interactionCount, 0);
  const observed = [...connection.records.flatMap((record) => record.occurredAt ? [record.occurredAt] : []), ...Object.values(relationshipDetails).flatMap((detail) => [detail.firstObservedAt, detail.latestObservedAt].filter((value): value is string => Boolean(value)))];
  const relationshipTypes = [...new Set(connection.records.filter((record) => record.kind === "RELATIONSHIP").map((record) => titleCase(record.label)))];
  return <section className="network-rail-panel network-connection-detail"><header><FileSearch aria-hidden="true" /><div><span className="eyebrow">Why NexusTrace shows this</span><h2>{connection.sourceLabel} ↔ {connection.targetLabel}</h2></div></header><dl className="network-compact-facts"><div><dt>Relationship type</dt><dd>{relationshipTypes.length ? relationshipTypes.join(", ") : "Activity-derived connection"}</dd></div><div><dt>Entities</dt><dd>{connection.sourceLabel} ↔ {connection.targetLabel}</dd></div><div><dt>Relationship tier</dt><dd>{connection.strength ? titleCase(connection.strength) : "Activity-derived"}</dd></div><div><dt>Verification</dt><dd>{titleCase(connection.verification)}</dd></div><div><dt>Reported interactions</dt><dd>{relationshipInteractions ? `${relationshipInteractions} relationship-reported · ` : ""}{activityInteractions} underlying activity record{activityInteractions === 1 ? "" : "s"}</dd></div><div><dt>First / latest observed</dt><dd>{observed.length ? `${formatMoment([...observed].sort()[0] ?? null)} → ${formatMoment([...observed].sort().at(-1) ?? null)}` : "Not recorded"}</dd></div><div><dt>Bundled activity</dt><dd>{connection.counts.calls} calls · {connection.counts.messages} messages · {connection.counts.emails} emails · {connection.counts.digitalContacts} digital · {connection.counts.financial} transactions</dd></div></dl>{provenanceLoading ? <p className="workspace-widget-muted" role="status">Loading authorized relationship provenance…</p> : null}<ol className="network-record-list">{connection.records.map((record) => {
    const detail = record.kind === "RELATIONSHIP" ? relationshipDetails[record.id] : undefined;
    return <li key={record.id}><div><strong>{titleCase(record.label)}</strong><time>{formatMoment(record.occurredAt)}</time></div><p>Source record: {record.kind} · {record.id}</p><p>Verification: {titleCase(record.verification)} · Interactions: {record.interactionCount}</p>{detail ? <dl className="network-record-provenance"><div><dt>Entities</dt><dd>{detail.sourceEntity.displayLabel} → {detail.targetEntity.displayLabel}</dd></div><div><dt>Observed</dt><dd>{formatMoment(detail.firstObservedAt)} → {formatMoment(detail.latestObservedAt)}</dd></div><div><dt>Department / creator</dt><dd>{detail.departmentName} · {detail.createdByName}</dd></div><div><dt>Verified by</dt><dd>{detail.verifiedByName ?? "Not verified"}{detail.verifiedAt ? ` · ${formatMoment(detail.verifiedAt)}` : ""}</dd></div></dl> : record.kind === "RELATIONSHIP" && !provenanceLoading ? <p>Source unavailable.</p> : null}{detail?.provenance.length ? <ul className="network-provenance-list">{detail.provenance.map((source) => <li key={source.id}><Link href={`/api/evidence/${source.evidenceId}`} target="_blank">{source.evidenceFilename}</Link><span>{source.sourceFirNumber} · {titleCase(source.evidenceVerificationState)}</span>{source.note ? <span>{source.note}</span> : null}</li>)}</ul> : detail && !provenanceLoading ? <p>Evidence provenance unavailable.</p> : null}{record.durationSeconds !== null ? <p>Duration {Math.floor(record.durationSeconds / 60)}m {record.durationSeconds % 60}s</p> : null}{record.amount !== null ? <p>{record.currency ?? ""} {record.amount.toLocaleString("en-IN")}</p> : null}{record.sourceLocation && record.destinationLocation ? <dl className="network-location-pair"><LocationResolution label={connection.sourceLabel} status={record.sourceLocation.status} location={record.sourceLocation.observation?.locationLabel ?? null} distance={record.sourceLocation.temporalDistanceSeconds} /><LocationResolution label={connection.targetLabel} status={record.destinationLocation.status} location={record.destinationLocation.observation?.locationLabel ?? null} distance={record.destinationLocation.temporalDistanceSeconds} /></dl> : null}<footer>{record.caseFirNumber ? <Link href={`/cases/${record.caseId}`}>{record.caseFirNumber}</Link> : <span>Related Case/FIR unavailable</span>}{record.sourceEvidenceId ? <Link href={`/api/evidence/${record.sourceEvidenceId}`} target="_blank">Inspect source evidence</Link> : record.kind !== "RELATIONSHIP" ? <span>Evidence source unavailable</span> : null}</footer></li>;
  })}</ol></section>;
}

export function AnalystContext({ projection, canReview }: { projection: SerializedGeographicProjection; canReview: boolean }) {
  return <section className="network-rail-panel"><header><ShieldCheck aria-hidden="true" /><div><span className="eyebrow">Analyst context</span><h2>Investigative leads</h2></div></header>{projection.findings.length === 0 ? <div className="network-inline-empty"><strong>NO FINDINGS</strong><span>No investigative findings are available for the current context.</span></div> : <ul className="network-findings-list">{projection.findings.slice(0, 4).map((finding) => <li key={finding.id}><strong>{finding.title}</strong><span>{titleCase(finding.category)} · {titleCase(finding.reviewStatus)}</span><span>Generated {formatMoment(finding.generatedAt)} · {finding.supportingRecordCount} source record{finding.supportingRecordCount === 1 ? "" : "s"} · {finding.evidenceCount} evidence item{finding.evidenceCount === 1 ? "" : "s"}</span><span>{finding.caseId && finding.caseFirNumber ? <Link href={`/cases/${finding.caseId}`}>Open {finding.caseFirNumber}</Link> : "Related Case/FIR unavailable"} · <Link href="/investigations">{canReview ? "Review source basis" : "View source basis"}</Link></span></li>)}</ul>}</section>;
}

export function InvestigationActions({ focusType, canSubmitIncident, canCreateIncident, canReviewIncident, canCrossVerify }: { focusType: GraphEntityType; canSubmitIncident: boolean; canCreateIncident: boolean; canReviewIncident: boolean; canCrossVerify: boolean }) {
  return <section className="network-rail-panel"><header><Crosshair aria-hidden="true" /><div><span className="eyebrow">Investigation actions</span><h2>Continue analysis</h2></div></header><div className="network-action-list"><Link href="#network-timeline">Open timeline</Link><Link href="/investigations">Open investigation workspace</Link>{canSubmitIncident ? <Link href="/incidents">Submit incident contribution</Link> : null}{canCreateIncident ? <Link href="/incidents">Create department incident</Link> : null}{canReviewIncident ? <Link href="/incidents">Review department submissions</Link> : null}{canCrossVerify ? <Link href="/incidents">Review cross-verification</Link> : null}<Link href="/cases">Open authorized cases</Link></div><p className="workspace-widget-muted">Only capabilities granted to the signed-in role are shown; every action is re-authorized on the server. Current focus type: {titleCase(focusType)}.</p></section>;
}

export function SignalPanel({ eyebrow, title, facts }: { eyebrow: string; title: string; facts: Array<[string, string | number]> }) {
  return <article className="workspace-widget-panel network-signal-panel"><header><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></header><dl className="workspace-facts">{facts.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>;
}

export function RelatedCasesPanel({ projection }: { projection: SerializedGeographicProjection }) {
  const cases = new Map<string, string>();
  for (const activity of projection.activities) if (activity.caseId && activity.caseFirNumber) cases.set(activity.caseId, activity.caseFirNumber);
  return <article className="workspace-widget-panel network-signal-panel"><header><p className="eyebrow">Related cases</p><h2>Authorized case context</h2></header>{cases.size === 0 ? <p className="workspace-widget-muted">No case-linked activity in this window.</p> : <ul className="network-related-cases">{[...cases].map(([id, fir]) => <li key={id}><Link href={`/cases/${id}`}>{fir}</Link></li>)}</ul>}</article>;
}
