"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { CaseSummary } from "@/domain/case";
import type { ReportPage, ReportSummary } from "@/domain/report";

export function ReportsConsole({ cases, initial }: { cases: CaseSummary[]; initial: ReportPage }) {
  const router = useRouter();
  const [items, setItems] = useState(initial.items); const [nextCursor, setNextCursor] = useState(initial.nextCursor); const [caseId, setCaseId] = useState(cases[0]?.id ?? ""); const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const generate = async () => { setBusy(true); setError(null); try { const response = await fetch("/api/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ caseId, title: title || undefined }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to generate report."); router.push(`/reports/${payload.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to generate report."); } finally { setBusy(false); } };
  const load = async () => { if (!nextCursor) return; const response = await fetch(`/api/reports?cursor=${nextCursor}`); if (!response.ok) return; const payload: ReportPage = await response.json(); setItems((current) => [...current, ...payload.items]); setNextCursor(payload.nextCursor); };
  return <div className="reports-console"><section className="report-generate"><header><p className="panel-kicker">Deterministic snapshot</p><h2>Generate investigation report</h2><p>Only authorized, bounded case data is captured. Findings remain separate from verified information.</p></header><label>Case / FIR<select value={caseId} onChange={(e) => setCaseId(e.target.value)}>{cases.map((item) => <option key={item.id} value={item.id}>{item.firNumber} · {item.title}</option>)}</select></label><label>Report title (optional)<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Investigation report" /></label><button className="primary-button" disabled={!caseId || busy} onClick={() => void generate()}>{busy ? "Generating immutable snapshot…" : "Generate report"}</button>{error ? <p className="form-error">{error}</p> : null}</section><section className="report-list"><header><p className="panel-kicker">Authorized report history</p><h2>Reports</h2></header>{items.length ? <ul>{items.map((item: ReportSummary) => <li key={item.id}><Link href={`/reports/${item.id}`}><strong>{item.reportNumber}</strong><span>{item.title}</span><small>{item.firNumber} · {item.departmentName} · v{item.version} · {new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.generatedAt))}</small></Link></li>)}</ul> : <p>No authorized reports yet. Generate a bounded case snapshot to begin.</p>}{nextCursor ? <button className="secondary-button" onClick={() => void load()}>Load more</button> : null}</section></div>;
}
