"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { AuditEventPage, AuditEventView } from "@/domain/audit";

type Options = { actors: Array<{ id: string; displayName: string }>; departments: Array<{ id: string; name: string; code: string }>; actions: string[]; targetTypes: string[] };
function stamp(value: Date | string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)); }
function recordLink(type: string, id: string | null) { if (!id) return null; if (type === "CASE") return `/cases/${id}`; if (type === "PERSON") return `/people/${id}`; if (type === "INCIDENT") return `/incidents/${id}`; if (type === "GRAPH_ENTITY" || type === "RELATIONSHIP") return `/network?focus=${id}`; return null; }

function AuditRow({ event }: { event: AuditEventView }) {
  const href = recordLink(event.targetType, event.targetId);
  const details = event.metadata ? JSON.stringify(event.metadata, null, 2) : null;
  return <article className="audit-event"><header><time dateTime={new Date(event.createdAt).toISOString()}>{stamp(event.createdAt)}</time><strong>{event.action}</strong><span className={`audit-outcome audit-outcome--${event.outcome.toLowerCase()}`}>{event.outcome}</span></header><dl><div><dt>Actor</dt><dd>{event.actor ? `${event.actor.displayName} · ${event.actor.role.replaceAll("_", " ")}` : "System or removed user"}</dd></div><div><dt>Department</dt><dd>{event.department ? `${event.department.name} · ${event.department.code}` : "—"}</dd></div><div><dt>Affected resource</dt><dd>{href ? <Link href={href}>{event.targetType} · {event.targetId}</Link> : `${event.targetType}${event.targetId ? ` · ${event.targetId}` : ""}`}</dd></div><div><dt>Related records</dt><dd>{event.relatedCaseId ? <Link href={`/cases/${event.relatedCaseId}`}>Case</Link> : null}{event.relatedCaseId && event.relatedIncidentId ? " · " : null}{event.relatedIncidentId ? <Link href={`/incidents/${event.relatedIncidentId}`}>Incident</Link> : null}{!event.relatedCaseId && !event.relatedIncidentId ? "—" : null}</dd></div>{event.reason ? <div><dt>Reason / context</dt><dd>{event.reason}</dd></div> : null}</dl>{details ? <details><summary>Safe recorded context</summary><pre>{details}</pre></details> : null}</article>;
}

export function AuditConsole({ initialPage, options }: { initialPage: AuditEventPage; options: Options }) {
  const [items, setItems] = useState(initialPage.items); const [cursor, setCursor] = useState(initialPage.nextCursor); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [filters, setFilters] = useState({ actorId: "", departmentId: "", action: "", targetType: "", relatedRecordId: "", startTime: "", endTime: "" });
  const query = useMemo(() => new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString(), [filters]);
  const load = async (append = false, next?: string | null) => { setLoading(true); setError(null); try { const params = new URLSearchParams(query); params.set("limit", "30"); if (next) params.set("cursor", next); const response = await fetch(`/api/audit?${params}`, { credentials: "same-origin" }); const payload: AuditEventPage & { error?: string } = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to load audit events."); setItems((current) => append ? [...current, ...payload.items] : payload.items); setCursor(payload.nextCursor); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load audit events."); } finally { setLoading(false); } };
  return <section className="audit-console"><form className="audit-filters" onSubmit={(event) => { event.preventDefault(); void load(); }}><label>From<input type="datetime-local" value={filters.startTime} onChange={(event) => setFilters((current) => ({ ...current, startTime: event.target.value }))} /></label><label>To<input type="datetime-local" value={filters.endTime} onChange={(event) => setFilters((current) => ({ ...current, endTime: event.target.value }))} /></label><label>Actor<select value={filters.actorId} onChange={(event) => setFilters((current) => ({ ...current, actorId: event.target.value }))}><option value="">All actors</option>{options.actors.map((actor) => <option key={actor.id} value={actor.id}>{actor.displayName}</option>)}</select></label><label>Department<select value={filters.departmentId} onChange={(event) => setFilters((current) => ({ ...current, departmentId: event.target.value }))}><option value="">All departments</option>{options.departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label>Action<select value={filters.action} onChange={(event) => setFilters((current) => ({ ...current, action: event.target.value }))}><option value="">All actions</option>{options.actions.map((action) => <option key={action} value={action}>{action}</option>)}</select></label><label>Resource type<select value={filters.targetType} onChange={(event) => setFilters((current) => ({ ...current, targetType: event.target.value }))}><option value="">All types</option>{options.targetTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label>Related case / incident<input value={filters.relatedRecordId} onChange={(event) => setFilters((current) => ({ ...current, relatedRecordId: event.target.value }))} placeholder="Record UUID" /></label><button className="secondary-button" type="submit">Apply filters</button></form>{error ? <section className="state-panel state-panel--error" role="alert"><h2>Audit history unavailable</h2><p>{error}</p></section> : null}<div className="audit-events">{items.map((event) => <AuditRow key={event.id} event={event} />)}</div>{items.length === 0 && !error ? <section className="state-panel"><h2>No audit events found</h2><p>No immutable audit records match these authorized filters.</p></section> : null}{cursor ? <button className="secondary-button" type="button" disabled={loading} onClick={() => void load(true, cursor)}>{loading ? "Loading…" : "Load more audit events"}</button> : null}</section>;
}
